language: android
dist: trusty
android:
 licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - android-sdk-license-c81a61d9
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-19
    - android-29    
    - sys-img-x86-android-29
    - extra-android-m2repository
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-29
    - android list sdk --extended --no-ui --all
before_script:
    # Launch emulator before the execution
    - echo no | android create avd --force -n test -t android-29 --abi google_apis/armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - ./gradlew build check